name: hvv_meldapplicatie
description: "Een Flutter-project voor Hart Voor Verkeer"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  mapbox_maps_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoHVV.png
    - assets/images/logoHVV2.png

  fonts:
    - family: Offside
      fonts:
        - asset: assets/fonts/Offside-Regular.ttf

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
