name: hvv_meldapplicatie
description: "Een Flutter-project voor Hart Voor Verkeer"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  mapbox_maps_flutter: ^2.0.0
  geolocator: ^14.0.2
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoHVV.png
    - assets/images/logoHVV2.png
    - assets/icons/arrow-prev-svgrepo-com.svg
    - assets/images/icoon1.png
    - assets/images/icoon2.png
    - assets/images/icoon3.png

    - assets/images/logoHVV2.png
    - ./.env

  fonts:
    - family: Offside
      fonts:
        - asset: assets/fonts/Offside-Regular.ttf

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
